export const emptyIconClass: string = 'mb-2 text-[2.5rem] opacity-50'
export const emptySubClass: string = 'max-w-[400px] text-eyebrow text-[var(--c-text-muted)]'

export const pageShellClass: string = 'flex min-h-screen flex-col bg-[var(--c-bg)]'
export const pageHeaderWrapClass: string = 'border-b border-[var(--c-border)] bg-[var(--c-surface)]/95 backdrop-blur'
export const pageHeaderClass: string = 'flex flex-wrap items-start justify-between gap-4 px-6 py-5'
export const pageEyebrowClass: string = 'text-2xs font-semibold uppercase tracking-[0.08em] text-[var(--c-text-muted)]'
export const pageTitleClass: string = 'text-pagetitle font-bold text-[var(--c-text)]'
export const pageSubtitleClass: string = 'mt-1 max-w-3xl text-sm text-[var(--c-text-muted)]'
export const pageStatusRowClass: string = 'mt-3 flex flex-wrap gap-2'
export const pageActionRailClass: string = 'flex flex-wrap items-center gap-2'
export const workspaceClass: string = 'flex flex-1 overflow-hidden'
export const workspaceMainClass: string = 'flex-1 overflow-auto px-4 py-4 sm:px-6 sm:py-6'
export const shellSidebarClass: string = 'w-[232px] shrink-0 border-r border-[var(--c-border)] bg-[var(--c-surface)]/95 px-4 py-5'
export const sidebarGroupLabelClass: string = 'px-3 pb-3 text-[0.68rem] font-semibold uppercase tracking-[0.08em] text-[var(--c-text-muted)]'
export const sidebarNavClass: string = 'flex flex-col gap-1'
export const sidebarItemClass: string = 'flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium text-[var(--c-text-muted)] transition hover:bg-[var(--c-status-neutral-bg)] hover:text-[var(--c-brand)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--c-brand)] focus-visible:ring-offset-2'
export const sidebarItemActiveClass: string = 'bg-[var(--c-status-neutral-bg)] text-[var(--c-brand)] shadow-[inset_3px_0_0_var(--c-brand)]'

export const loadingClass: string = 'flex flex-col items-center justify-center gap-4 px-6 py-12 text-[var(--c-text-muted)]'
export const spinnerClass: string = 'h-8 w-8 animate-spin rounded-full border-[3px] border-[var(--c-border)] border-t-[var(--c-brand)]'
export const emptyCardClass: string = 'flex h-full min-h-[180px] flex-col items-center justify-center gap-3 rounded-lg border border-dashed border-[var(--c-border)] bg-[var(--c-surface)] px-8 py-12 text-center text-[var(--c-text-muted)]'

export const surfacePanelClass: string = 'rounded-lg border border-[var(--c-border)] bg-[var(--c-surface)] p-4 shadow-base'
export const heroCardClass: string = 'rounded-xl border border-[var(--c-border)] bg-[var(--c-surface)] p-5 shadow-base'
export const heroCardDenseClass: string = 'rounded-xl border border-[var(--c-border)] bg-[var(--c-surface)] p-4 shadow-base'
export const cardTitleClass: string = 'text-base font-semibold text-[var(--c-text)]'
export const cardSubClass: string = 'mt-1 text-sm text-[var(--c-text-muted)]'
export const moduleHeaderCardClass: string = `${heroCardClass} flex flex-col gap-2`
export const moduleEyebrowClass: string = 'text-2xs font-semibold uppercase tracking-[0.06em] text-[var(--c-text-muted)]'
export const moduleHeaderActionsClass: string = 'flex flex-wrap items-center gap-2'
export const splitPanelClass: string = 'grid gap-4 lg:grid-cols-[minmax(0,1.5fr)_320px]'
export const metricGridClass: string = 'grid gap-3 lg:grid-cols-2 xl:grid-cols-4'
export const metricCardClass: string = 'rounded-lg border p-4 shadow-base'
export const metricCardLabelClass: string = 'text-2xs font-semibold uppercase tracking-[0.05em] text-[var(--c-text-muted)]'
export const metricCardValueClass: string = 'mt-2 text-3xl font-bold leading-none text-[var(--c-text)]'
export const metricCardMetaClass: string = 'mt-2 text-xs text-[var(--c-text-muted)]'
export const statusChipRowClass: string = 'flex flex-wrap items-center gap-2'
export const statusChipClass: string = 'inline-flex items-center rounded-full border px-2.5 py-1 text-xs font-semibold'
export const infoBannerClass: string = 'flex flex-wrap items-center gap-2 rounded-lg border px-3 py-2 text-sm'
export const infoBannerErrorClass: string = `${infoBannerClass} border-[var(--c-status-bad-strong-border)] bg-[var(--c-status-bad-bg)] text-[var(--c-status-bad-text)]`
export const infoBannerWarnClass: string = `${infoBannerClass} border-[var(--c-status-warn-border)] bg-[var(--c-status-warn-bg)] text-[var(--c-status-warn-text)]`
export const infoBannerInfoClass: string = `${infoBannerClass} border-[var(--c-status-info-border)] bg-[var(--c-status-info-bg)] text-[var(--c-status-info-text)]`
export const infoBannerNeutralClass: string = `${infoBannerClass} border-[var(--c-status-neutral-border)] bg-[var(--c-status-neutral-bg)] text-[var(--c-status-neutral-text)]`

export const chartPaneClass: string = 'mb-1 border-b border-[var(--c-border)] pb-4 last:mb-0 last:border-b-0 last:pb-0'
export const chartPaneTitleClass: string = 'mb-2 flex items-center gap-3 text-eyebrow font-semibold text-[var(--c-text-muted)]'
export const chartHintClass: string = 'mt-1 text-2xs italic text-[var(--c-text-muted)]'
export const chartNClass: string = 'text-xs font-normal'
export const chartOocClass: string = 'text-xs font-semibold text-[var(--spc-red)]'

export const sectionTitleClass: string = 'text-lg font-semibold text-[var(--c-text)]'
export const sectionSubClass: string = 'mt-1 text-sm text-[var(--c-text-muted)]'

export const flowCanvasClass: string = 'relative min-h-[500px] h-[calc(100vh-280px)] overflow-hidden rounded-lg border border-[var(--c-border)] bg-[var(--c-bg)]'
export const flowLegendClass: string = 'absolute left-3 top-3 z-10 flex flex-wrap items-center gap-3 rounded-md border border-[var(--c-border)] bg-white/90 px-3 py-2 text-xs backdrop-blur'
export const legendItemClass: string = 'flex items-center gap-1.5 text-[var(--c-text-muted)]'
export const legendDotClass: string = 'h-2.5 w-2.5 shrink-0 rounded-full'
export const legendHintClass: string = 'ml-1 border-l border-[var(--c-border)] pl-3 italic text-[var(--c-text-muted)]'

export const chartsLayoutClass: string = 'flex flex-col gap-5'
export const chartsHeaderClass: string = `${heroCardClass} flex flex-col gap-4`
export const chartsHeaderTopClass: string = 'flex flex-wrap items-start justify-between gap-4'
export const chartsHeaderRightClass: string = 'flex flex-wrap items-center gap-2'
export const chartsTitleClass: string = 'text-title font-bold text-[var(--c-text)]'
export const chartsMaterialClass: string = 'text-sm text-[var(--c-text-muted)]'
export const chartsMicMetaClass: string = 'mt-1 flex gap-4 text-eyebrow text-[var(--c-text-muted)]'
export const chartsMainClass: string = `${heroCardClass}`
export const chartsWorkspaceClass: string = 'grid items-start gap-5 lg:grid-cols-[minmax(0,1.6fr)_360px]'
export const chartsBottomClass: string = 'grid items-start gap-5 lg:grid-cols-[minmax(0,1fr)_360px]'
export const sideStackClass: string = 'flex flex-col gap-4'
export const evidenceRailClass: string = 'flex flex-col gap-4'
export const settingsRailClass: string = `${heroCardDenseClass} space-y-3`
export const settingsRailRowClass: string = 'flex flex-wrap items-center gap-2'
export const settingsRailLabelClass: string = 'text-2xs font-semibold uppercase tracking-[0.05em] text-[var(--c-text-muted)]'
export const strataSectionClass: string = `${heroCardDenseClass}`
export const strataSectionHeaderClass: string = 'mb-4 flex flex-wrap items-center justify-between gap-2 border-b border-[var(--c-border)] pb-3'
export const strataSectionTitleClass: string = 'text-sm font-semibold text-[var(--c-text)]'
export const strataSectionMetaClass: string = 'text-xs text-[var(--c-text-muted)]'
export const comparisonGridClass: string = 'grid gap-4 lg:grid-cols-2'

export const toggleGroupClass: string = 'flex items-center gap-1.5'
export const toggleLabelClass: string = 'text-eyebrow text-[var(--c-text-muted)]'
export const toggleButtonBaseClass: string = 'rounded-[5px] border border-[var(--c-border)] bg-[var(--c-surface)] px-3 py-1.5 text-eyebrow font-medium text-[var(--c-text-muted)] transition hover:border-[var(--c-brand)] hover:text-[var(--c-brand)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--c-brand)] focus-visible:ring-offset-2'
export const toggleButtonActiveClass: string = 'border-[var(--c-brand)] bg-[var(--c-brand)] text-white hover:text-white'
export const toggleButtonResetClass: string = 'text-xs text-[var(--c-text-muted)]'
export const toggleAutoClass: string = 'text-xs italic text-[var(--c-text-muted)]'
export const checkboxLabelClass: string = 'flex cursor-pointer select-none items-center gap-1.5 text-eyebrow text-[var(--c-text-muted)]'
export const chartPairClass: string = 'grid gap-4'

export const buttonBaseClass: string = 'inline-flex items-center justify-center rounded-md border border-transparent px-3 py-2 text-sm font-medium transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--c-brand)] focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50'
export const buttonSmClass: string = 'px-2.5 py-1.5 text-xs'
export const buttonPrimaryClass: string = 'bg-[var(--c-brand)] text-white hover:opacity-90'
export const buttonSecondaryClass: string = 'border-[var(--c-border)] bg-[var(--c-surface)] text-[var(--c-text)] hover:border-[var(--c-brand)] hover:text-[var(--c-brand)]'
export const buttonDangerClass: string = 'bg-red-600 text-white hover:bg-red-700'
export const buttonGhostClass: string = 'border-[var(--c-border)] bg-transparent text-[var(--c-text-muted)] hover:border-[var(--c-brand)] hover:text-[var(--c-brand)]'
export const fieldHelpClass: string = 'text-xs text-[var(--c-text-muted)]'
export const fieldValidationErrorClass: string = 'text-xs font-medium text-red-700'
export const inputBaseClass: string = 'h-10 w-full rounded-md border border-[var(--c-border)] bg-[var(--c-surface)] px-3 text-sm text-[var(--c-text)] outline-none transition focus:border-[var(--c-brand)] focus-visible:ring-2 focus-visible:ring-[var(--c-brand)]/25'
export const inputSmClass: string = 'h-9 px-2.5 text-sm'
export const selectClass: string = `${inputBaseClass} pr-8`
export const dateInputClass: string = `${inputBaseClass}`
export const filterBarClass: string = 'grid gap-4 border-b border-[var(--c-border)] bg-[var(--c-surface)] px-6 py-5 lg:grid-cols-[minmax(0,1.55fr)_minmax(0,1fr)]'
export const filterSectionClass: string = 'grid gap-4 sm:grid-cols-2 lg:grid-cols-4'
export const filterActionsClass: string = 'grid gap-4 lg:grid-cols-[minmax(0,1fr)_auto]'
export const filterCardClass: string = 'rounded-xl border border-[var(--c-border)] bg-[var(--c-status-neutral-bg)]/80 p-3'
export const filterGroupClass: string = 'flex min-w-[180px] flex-col gap-1.5'
export const filterLabelClass: string = 'text-2xs font-semibold uppercase tracking-[0.05em] text-[var(--c-text-muted)]'
export const filterValueClass: string = 'text-sm font-medium text-[var(--c-text)]'
export const filterMetaClass: string = 'flex flex-wrap items-center gap-2'
export const badgeBaseClass: string = 'inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium'
export const badgeGreenClass: string = 'bg-[var(--c-status-ok-bg)] text-[var(--c-status-ok-text)]'
export const badgeAmberClass: string = 'bg-[var(--c-status-warn-bg)] text-[var(--c-status-warn-text)]'
export const badgeBlueClass: string = 'bg-[var(--c-status-info-bg)] text-[var(--c-status-info-text)]'
export const badgeSlateClass: string = 'bg-[var(--c-status-neutral-bg)] text-[var(--c-status-neutral-text)]'

export const filterStepClass: string = 'flex items-start gap-3'
export const filterStepNumClass: string = 'mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-[var(--c-brand)] text-[0.65rem] font-bold text-white'
export const filterStepNumInactiveClass: string = 'mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full border border-[var(--c-border)] bg-[var(--c-status-neutral-bg)] text-[0.65rem] font-semibold text-[var(--c-text-muted)]'
export const filterStepBodyClass: string = 'min-w-0 flex-1'

export const scorecardLayoutClass: string = 'flex flex-col gap-5'
export const scorecardHeaderClass: string = `${heroCardClass} flex flex-col gap-2`
export const scorecardTitleClass: string = 'text-title font-semibold text-[var(--c-text)]'
export const scorecardPlantClass: string = 'text-base font-normal text-[var(--c-text-muted)]'
export const scorecardSubClass: string = 'text-sm text-[var(--c-text-muted)]'
export const scorecardSummaryClass: string = 'grid gap-3 lg:grid-cols-2 xl:grid-cols-5'
export const scorecardKpiClass: string = 'rounded-xl border p-4 shadow-base'
export const kpiValueClass: string = 'text-2xl font-bold'
export const kpiLabelClass: string = 'mt-1 block text-xs font-medium text-[var(--c-text-muted)]'
export const scorecardToggleClass: string = 'flex flex-wrap gap-2'
export const stabilityNoteClass: string = 'text-sm text-[var(--c-text-muted)]'
export const scorecardTableWrapClass: string = `${heroCardClass} space-y-4`
export const scorecardTableHeaderClass: string = 'flex flex-wrap items-center gap-2'
export const scorecardCountClass: string = 'mr-auto text-sm text-[var(--c-text-muted)]'
export const pillValueClass: string = 'inline-flex rounded-full px-2 py-0.5 text-xs font-semibold'
export const statusPillClass: string = 'inline-flex rounded-full px-2 py-0.5 text-xs font-medium'
export const scorecardEvidenceClass: string = 'grid gap-4 lg:grid-cols-[minmax(0,1.4fr)_320px]'
export const scorecardSidebarClass: string = `${heroCardDenseClass} space-y-3`

export const compareViewClass: string = 'flex flex-col gap-4'
export const compareInputsClass: string = `${heroCardDenseClass} flex flex-col gap-3`
export const compareInputRowClass: string = 'flex items-end gap-2'
export const compareInputLabelClass: string = 'mb-1 block text-xs font-semibold uppercase tracking-[0.04em] text-[var(--c-text-muted)]'
export const compareSummaryClass: string = 'flex flex-wrap gap-2'
export const compareBadgeClass: string = 'inline-flex rounded-full bg-[var(--c-status-neutral-bg)] px-3 py-1 text-xs font-medium text-[var(--c-text-muted)]'
export const compareBadgeCommonClass: string = 'bg-[var(--c-status-ok-bg)] text-[var(--c-status-ok-text)]'

export const correlationViewClass: string = 'flex flex-col gap-4'
export const controlsRowClass: string = 'flex flex-wrap items-center gap-3'
export const inlineLabelClass: string = 'flex items-center gap-2 text-sm text-[var(--c-text)]'
export const correlationMetaClass: string = 'text-sm text-[var(--c-text-muted)]'

export const msaViewClass: string = 'flex flex-col gap-4'
export const msaSetupClass: string = `${surfacePanelClass} grid gap-3 md:grid-cols-2`
export const msaSetupRowClass: string = 'flex items-center justify-between gap-3'
export const msaDataClass: string = `${surfacePanelClass}`
export const msaTextareaClass: string = 'min-h-[220px] w-full rounded-md border border-[var(--c-border)] bg-[var(--c-surface)] px-3 py-2 text-sm text-[var(--c-text)] outline-none focus:border-[var(--c-brand)]'
export const msaResultsClass: string = `${surfacePanelClass} space-y-3`
export const msaTableClass: string = 'w-full border-collapse text-sm'
export const msaVerdictClass: string = 'flex flex-wrap items-baseline gap-2 text-lg font-semibold'
export const msaNdcClass: string = 'text-sm text-[var(--c-text)]'

export const auditPanelClass: string = `${surfacePanelClass} space-y-3`
export const auditHeaderClass: string = 'flex flex-wrap items-start justify-between gap-3'
export const auditTitleClass: string = 'text-sm font-semibold text-[var(--c-text)]'
export const auditSubtitleClass: string = 'text-xs text-[var(--c-text-muted)]'
export const auditMetaClass: string = 'flex flex-wrap gap-3 text-xs text-[var(--c-text-muted)]'
export const auditDiffClass: string = 'grid gap-2 md:grid-cols-2'
export const auditDiffCardClass: string = 'flex flex-col gap-1 rounded-md border border-[var(--c-border)] bg-[var(--c-status-neutral-bg)] p-3 text-sm text-[var(--c-text)]'
export const auditDiffCardActiveClass: string = 'border-[var(--c-status-info-border)] bg-[var(--c-status-info-bg)]'
export const auditDiffLabelClass: string = 'text-2xs font-semibold uppercase tracking-[0.04em] text-[var(--c-text-muted)]'
export const auditEmptyClass: string = 'rounded-md bg-[var(--c-status-neutral-bg)] p-3 text-sm text-[var(--c-text-muted)]'
export const auditListClass: string = 'space-y-2'
export const auditItemClass: string = 'flex items-center justify-between gap-3 rounded-md border border-[var(--c-border)] px-3 py-2'
export const auditItemMainClass: string = 'flex flex-wrap items-center gap-3 text-sm text-[var(--c-text)]'

export const modalBackdropClass: string = 'fixed inset-0 z-[70] flex items-center justify-center bg-[var(--c-text)]/40 p-4'
export const modalClass: string = 'w-full max-w-xl rounded-xl border border-[var(--c-border)] bg-[var(--c-surface)] p-5 shadow-2xl'
export const modalHeaderClass: string = 'mb-4 flex items-start justify-between gap-3'
export const modalTitleClass: string = 'text-lg font-semibold text-[var(--c-text)]'
export const modalSubtitleClass: string = 'mt-1 text-sm text-[var(--c-text-muted)]'
export const modalFormClass: string = 'space-y-4'
export const modalTextareaClass: string = 'min-h-[120px] w-full rounded-md border border-[var(--c-border)] bg-[var(--c-surface)] px-3 py-2 text-sm text-[var(--c-text)] outline-none focus:border-[var(--c-brand)] focus-visible:ring-2 focus-visible:ring-[var(--c-brand)]/25'
export const modalActionsClass: string = 'flex justify-end gap-2'
export const exclusionTargetClass: string = 'mb-4 flex flex-wrap gap-2 rounded-md bg-[var(--c-status-neutral-bg)] px-3 py-2 text-sm text-[var(--c-text)]'
export const exclusionTargetLabelClass: string = 'text-xs font-semibold uppercase tracking-[0.04em] text-[var(--c-text-muted)]'

export const rollingPanelClass: string = `${surfacePanelClass} space-y-3`
export const rollingHeaderClass: string = 'flex flex-wrap items-center justify-between gap-3'
export const rollingTitleClass: string = 'text-sm font-semibold text-[var(--c-text)]'
export const rollingWindowLabelClass: string = 'flex items-center gap-2 text-sm text-[var(--c-text-muted)]'
export const rollingWindowInputClass: string = 'h-9 w-20 rounded-md border border-[var(--c-border)] bg-[var(--c-surface)] px-3 text-sm text-[var(--c-text)] outline-none focus:border-[var(--c-brand)] focus-visible:ring-2 focus-visible:ring-[var(--c-brand)]/25'
export const srOnlyClass: string = 'sr-only'

export const autoCleanLogClass: string = `${surfacePanelClass} space-y-2`
export const autoCleanHeaderClass: string = 'flex flex-wrap items-center gap-3'
export const autoCleanIterClass: string = 'text-sm text-[var(--c-text-muted)]'
