export const emptyStateClass = 'flex flex-col items-center justify-center gap-2 px-8 py-16 text-center text-[var(--c-text-muted)]'
export const emptyIconClass = 'mb-2 text-[2.5rem] opacity-50'
export const emptySubClass = 'max-w-[400px] text-[0.8125rem] text-[var(--c-text-muted)]'

export const loadingClass = 'flex flex-col items-center justify-center gap-4 px-6 py-12 text-[var(--c-text-muted)]'
export const spinnerClass = 'h-8 w-8 animate-spin rounded-full border-[3px] border-[var(--c-border)] border-t-[var(--c-brand)]'
export const emptyCardClass = 'flex h-full min-h-[180px] flex-col items-center justify-center gap-3 rounded-[var(--radius)] border border-dashed border-[var(--c-border)] bg-[var(--c-surface)] px-8 py-12 text-center text-[var(--c-text-muted)]'

export const surfacePanelClass = 'rounded-[var(--radius)] border border-[var(--c-border)] bg-[var(--c-surface)] p-4 shadow-[var(--shadow)]'
export const chartPaneClass = 'mb-1 border-b border-[var(--c-border)] pb-4 last:mb-0 last:border-b-0 last:pb-0'
export const chartPaneTitleClass = 'mb-2 flex items-center gap-3 text-[0.8125rem] font-semibold text-[var(--c-text-muted)]'
export const chartHintClass = 'mt-1 text-[0.7rem] italic text-[var(--c-text-muted)]'
export const chartNClass = 'text-xs font-normal'
export const chartOocClass = 'text-xs font-semibold text-[var(--spc-red)]'

export const sectionTitleClass = 'text-lg font-semibold text-[var(--c-text)]'
export const sectionSubClass = 'mt-1 text-sm text-[var(--c-text-muted)]'

export const flowCanvasClass = 'relative min-h-[500px] h-[calc(100vh-280px)] overflow-hidden rounded-[var(--radius)] border border-[var(--c-border)] bg-slate-50'
export const flowLegendClass = 'absolute left-3 top-3 z-10 flex flex-wrap items-center gap-3 rounded-md border border-[var(--c-border)] bg-white/90 px-3 py-2 text-xs backdrop-blur'
export const legendItemClass = 'flex items-center gap-1.5 text-[var(--c-text-muted)]'
export const legendDotClass = 'h-2.5 w-2.5 shrink-0 rounded-full'
export const legendHintClass = 'ml-1 border-l border-[var(--c-border)] pl-3 italic text-[var(--c-text-muted)]'

export const chartsLayoutClass = 'flex flex-col gap-5'
export const chartsHeaderClass = 'flex flex-wrap items-center justify-between gap-3 border-b border-[var(--c-border)] pb-3'
export const chartsHeaderRightClass = 'flex flex-wrap items-center gap-3'
export const chartsTitleClass = 'text-lg font-bold text-[var(--c-text)]'
export const chartsMaterialClass = 'text-sm text-[var(--c-text-muted)]'
export const chartsMicMetaClass = 'mt-1 flex gap-4 text-[0.78rem] text-[var(--c-text-muted)]'
export const chartsMainClass = `${surfacePanelClass}`
export const chartsBottomClass = 'grid items-start gap-5 lg:grid-cols-[1fr_1.6fr]'
export const sideStackClass = 'flex flex-col gap-4'

export const toggleGroupClass = 'flex items-center gap-1.5'
export const toggleLabelClass = 'text-[0.8rem] text-[var(--c-text-muted)]'
export const toggleButtonBaseClass = 'rounded-[5px] border border-[var(--c-border)] bg-[var(--c-surface)] px-3 py-1.5 text-[0.8rem] font-medium text-[var(--c-text-muted)] transition hover:border-[var(--c-brand)] hover:text-[var(--c-brand)]'
export const toggleButtonActiveClass = 'border-[var(--c-brand)] bg-[var(--c-brand)] text-white hover:text-white'
export const toggleButtonResetClass = 'text-xs text-[var(--c-text-muted)]'
export const toggleAutoClass = 'text-xs italic text-[var(--c-text-muted)]'
export const checkboxLabelClass = 'flex cursor-pointer select-none items-center gap-1.5 text-[0.78rem] text-[var(--c-text-muted)]'
export const chartPairClass = 'grid gap-4'

export const buttonBaseClass = 'inline-flex items-center justify-center rounded-md border border-transparent px-3 py-2 text-sm font-medium transition disabled:cursor-not-allowed disabled:opacity-50'
export const buttonSmClass = 'px-2.5 py-1.5 text-xs'
export const buttonPrimaryClass = 'bg-[var(--c-brand)] text-white hover:opacity-90'
export const buttonSecondaryClass = 'border-[var(--c-border)] bg-[var(--c-surface)] text-[var(--c-text)] hover:border-[var(--c-brand)] hover:text-[var(--c-brand)]'
export const buttonDangerClass = 'bg-red-600 text-white hover:bg-red-700'
export const buttonGhostClass = 'border-[var(--c-border)] bg-transparent text-[var(--c-text-muted)] hover:border-[var(--c-brand)] hover:text-[var(--c-brand)]'
export const inputBaseClass = 'h-10 w-full rounded-md border border-[var(--c-border)] bg-[var(--c-surface)] px-3 text-sm text-[var(--c-text)] outline-none transition focus:border-[var(--c-brand)]'
export const inputSmClass = 'h-9 px-2.5 text-sm'
export const selectClass = `${inputBaseClass} pr-8`
export const dateInputClass = `${inputBaseClass}`
export const filterBarClass = 'flex flex-wrap items-end gap-4 border-b border-[var(--c-border)] bg-[var(--c-surface)] px-5 py-4'
export const filterGroupClass = 'flex min-w-[180px] flex-col gap-1.5'
export const filterLabelClass = 'text-[0.72rem] font-semibold uppercase tracking-[0.05em] text-[var(--c-text-muted)]'
export const filterMetaClass = 'ml-auto flex items-center gap-2'
export const badgeBaseClass = 'inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium'
export const badgeGreenClass = 'bg-emerald-50 text-emerald-700'
export const badgeAmberClass = 'bg-amber-50 text-amber-700'
export const badgeBlueClass = 'bg-sky-50 text-sky-700'
export const badgeSlateClass = 'bg-slate-100 text-slate-700'

export const scorecardLayoutClass = 'flex flex-col gap-4'
export const scorecardHeaderClass = 'flex flex-col gap-1'
export const scorecardTitleClass = 'text-lg font-semibold text-[var(--c-text)]'
export const scorecardPlantClass = 'text-base font-normal text-[var(--c-text-muted)]'
export const scorecardSubClass = 'text-sm text-[var(--c-text-muted)]'
export const scorecardSummaryClass = 'grid gap-3 md:grid-cols-2 xl:grid-cols-5'
export const scorecardKpiClass = 'rounded-[var(--radius)] border p-4 shadow-[var(--shadow)]'
export const kpiValueClass = 'text-2xl font-bold'
export const kpiLabelClass = 'mt-1 block text-xs font-medium text-[var(--c-text-muted)]'
export const scorecardToggleClass = 'flex gap-2'
export const stabilityNoteClass = 'text-sm text-[var(--c-text-muted)]'
export const scorecardTableWrapClass = `${surfacePanelClass} space-y-3`
export const scorecardTableHeaderClass = 'flex flex-wrap items-center gap-2'
export const scorecardCountClass = 'mr-auto text-sm text-[var(--c-text-muted)]'
export const pillValueClass = 'inline-flex rounded-full px-2 py-0.5 text-xs font-semibold'
export const statusPillClass = 'inline-flex rounded-full px-2 py-0.5 text-xs font-medium'

export const compareViewClass = 'flex flex-col gap-4'
export const compareInputsClass = 'flex flex-col gap-3'
export const compareInputRowClass = 'flex items-end gap-2'
export const compareInputLabelClass = 'mb-1 block text-xs font-semibold uppercase tracking-[0.04em] text-[var(--c-text-muted)]'
export const compareSummaryClass = 'flex flex-wrap gap-2'
export const compareBadgeClass = 'inline-flex rounded-full bg-slate-100 px-3 py-1 text-xs font-medium text-slate-700'
export const compareBadgeCommonClass = 'bg-emerald-50 text-emerald-700'

export const correlationViewClass = 'flex flex-col gap-4'
export const controlsRowClass = 'flex flex-wrap items-center gap-3'
export const inlineLabelClass = 'flex items-center gap-2 text-sm text-[var(--c-text)]'
export const correlationMetaClass = 'text-sm text-[var(--c-text-muted)]'

export const msaViewClass = 'flex flex-col gap-4'
export const msaSetupClass = `${surfacePanelClass} grid gap-3 md:grid-cols-2`
export const msaSetupRowClass = 'flex items-center justify-between gap-3'
export const msaDataClass = `${surfacePanelClass}`
export const msaTextareaClass = 'min-h-[220px] w-full rounded-md border border-[var(--c-border)] bg-[var(--c-surface)] px-3 py-2 text-sm text-[var(--c-text)] outline-none focus:border-[var(--c-brand)]'
export const msaResultsClass = `${surfacePanelClass} space-y-3`
export const msaTableClass = 'w-full border-collapse text-sm'
export const msaVerdictClass = 'flex flex-wrap items-baseline gap-2 text-lg font-semibold'
export const msaNdcClass = 'text-sm text-[var(--c-text)]'

export const auditPanelClass = `${surfacePanelClass} space-y-3`
export const auditHeaderClass = 'flex flex-wrap items-start justify-between gap-3'
export const auditTitleClass = 'text-sm font-semibold text-[var(--c-text)]'
export const auditSubtitleClass = 'text-xs text-[var(--c-text-muted)]'
export const auditMetaClass = 'flex flex-wrap gap-3 text-xs text-[var(--c-text-muted)]'
export const auditDiffClass = 'grid gap-2 md:grid-cols-2'
export const auditDiffCardClass = 'flex flex-col gap-1 rounded-md border border-[var(--c-border)] bg-slate-50 p-3 text-sm text-[var(--c-text)]'
export const auditDiffCardActiveClass = 'border-sky-200 bg-sky-50'
export const auditDiffLabelClass = 'text-[0.7rem] font-semibold uppercase tracking-[0.04em] text-[var(--c-text-muted)]'
export const auditEmptyClass = 'rounded-md bg-slate-50 p-3 text-sm text-[var(--c-text-muted)]'
export const auditListClass = 'space-y-2'
export const auditItemClass = 'flex items-center justify-between gap-3 rounded-md border border-[var(--c-border)] px-3 py-2'
export const auditItemMainClass = 'flex flex-wrap items-center gap-3 text-sm text-[var(--c-text)]'

export const modalBackdropClass = 'fixed inset-0 z-[70] flex items-center justify-center bg-slate-950/40 p-4'
export const modalClass = 'w-full max-w-xl rounded-xl border border-[var(--c-border)] bg-[var(--c-surface)] p-5 shadow-2xl'
export const modalHeaderClass = 'mb-4 flex items-start justify-between gap-3'
export const modalTitleClass = 'text-lg font-semibold text-[var(--c-text)]'
export const modalSubtitleClass = 'mt-1 text-sm text-[var(--c-text-muted)]'
export const modalFormClass = 'space-y-4'
export const modalTextareaClass = 'min-h-[120px] w-full rounded-md border border-[var(--c-border)] bg-[var(--c-surface)] px-3 py-2 text-sm text-[var(--c-text)] outline-none focus:border-[var(--c-brand)]'
export const modalActionsClass = 'flex justify-end gap-2'
export const exclusionTargetClass = 'mb-4 flex flex-wrap gap-2 rounded-md bg-slate-50 px-3 py-2 text-sm text-[var(--c-text)]'
export const exclusionTargetLabelClass = 'text-xs font-semibold uppercase tracking-[0.04em] text-[var(--c-text-muted)]'

export const rollingPanelClass = `${surfacePanelClass} space-y-3`
export const rollingHeaderClass = 'flex flex-wrap items-center justify-between gap-3'
export const rollingTitleClass = 'text-sm font-semibold text-[var(--c-text)]'
export const rollingWindowLabelClass = 'flex items-center gap-2 text-sm text-[var(--c-text-muted)]'
export const rollingWindowInputClass = 'h-9 w-20 rounded-md border border-[var(--c-border)] bg-[var(--c-surface)] px-3 text-sm text-[var(--c-text)] outline-none focus:border-[var(--c-brand)]'

export const autoCleanLogClass = `${surfacePanelClass} space-y-2`
export const autoCleanHeaderClass = 'flex flex-wrap items-center gap-3'
export const autoCleanIterClass = 'text-sm text-[var(--c-text-muted)]'
